Module 4
rajrahman/DevOps-Course-Starter pull request #2
Opened 2020-12-16 01:31 UTC by rajrahman

2021-01-06 15:27 UTC, hugh-emerson requested changes
Mostly right but some small issues:
- The .poetry folder shouldn't be there
- You are missing a pyproject.toml file 
- You need to update the README with instructions to install poetry and run commands like `poetry run flask run`

See my other comments for details.

Also, this PR includes all of the module 3 changes but I've ignored them. You could have made the PR target the module 3 branch to avoid this.

2021-01-06 15:27 UTC, hugh-emerson commented on .poetry/bin/poetry
> +#!/usr/bin/env python
This `.poetry` folder shouldn't be in the codebase. It should just be installed on your system.

2021-01-06 15:27 UTC, hugh-emerson commented on Vagrantfile
> +      # TODO: Install pyenv prerequisites
This "TODO" comment is out of date. It's done now.

2021-01-06 15:27 UTC, hugh-emerson commented on Vagrantfile
> +      eval "$(pyenv init -)"
Instead of repeating these three lines, you could just `source ~/.profile` to run the file you've updated.

2021-01-06 15:27 UTC, hugh-emerson commented on Vagrantfile
> +      cd ~
You should already be in `~`

2021-01-06 15:27 UTC, hugh-emerson commented on Vagrantfile
> +      export PATH="$HOME/.poetry/bin:$PATH"
exporting this at the end of a shell script is pointless - environment variables are not persisted between shells.

But when you install poetry, it automatically updates `.profile` with this line, so all future shells will have poetry on the PATH.

2021-01-06 15:27 UTC, hugh-emerson commented on Vagrantfile
> +         pip install requests
Poetry handles all of your dependency management now - you don't need to do `pip` anything anymore. Delete these two lines.

What you need is a pyproject.toml file added to your codebase to list your project's dependencies. Run `poetry init` to create one. And you can run e.g. `poetry add requests` to update it with new dependencies. 

You could also see what it should look like here: https://github.com/CorndelWithSoftwire/DevOps-Course-Starter/blob/master/pyproject.toml

2021-02-08 22:57 UTC, closed without merging

2021-02-08 22:57 UTC, rajrahman commented
making requested changes